#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# ssh-agent
# run ssh agent at login, this is useful for caching ssh credentials
# WARNING: ssh-agent by itself is fine, but please note the security/usability
# tradeoffs of ssh-add afterwards!
if [[ -o login ]]; then
    eval $(ssh-agent) 2>&1 >/dev/null
fi
