#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source ~/.alias
export TERM=xterm-256color

export PYTHONSTARTUP=$HOME/.pystartup

# tty hack (thanks to Nicolas George)
# Basically, it restores terminal at the end of a pipeline,
# useful in the event that a process crashes and has modified terminal state
ttyctl -f

# allow comments on the command line, from:
# https://stackoverflow.com/questions/11670935/comments-in-command-line-zsh
setopt interactivecomments

# autocontinue suspended jobs with disown
setopt AUTO_CONTINUE

# Gurobi stuff
export GUROBI_HOME="/opt/gurobi752/linux64"
export PATH="${PATH}:${GUROBI_HOME}/bin"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${GUROBI_HOME}/lib"
export GRB_LICENSE_FILE=/home/gajjanag/gurobi.lic
