#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
source ~/.alias
export TERM=xterm-256color

export PYTHONSTARTUP=$HOME/.pystartup

# tty hack (thanks to Nicolas George)
# Basically, it restores terminal at the end of a pipeline,
# useful in the event that a process crashes and has modified terminal state
ttyctl -f
